### ISSUE TITLE
Use .witness.yml to configure witness

### ISSUE THREAD

**Issue by colek42** [testifysec/witness-install-action#4]
Currently, we configure witness by setting env vars with `core.exportVariable("ASDF", keyLocation);` There is a bash file which reads these vars and runs witness with cmd line args.

This does not work with local testing tools such as https://github.com/nektos/act for some reason.

We should write the configuration to a temporary file and the bash script should use the config values from that configuration file instead of env vars.

**Comment by developer-guy** [comment]
What I understand from this (please correct me If I'm wrong) is that we should accept the configuration file as one of the inputs we provide by installer action. Or should we just change the logic of the bash script by simply reading the configuration file instead of the environment variables, so we should create a configuration file instead of setting environment variables? Am I right?

**Comment by colek42** [comment]
- Create a config file during the install action.  If witness is already installed, we should rewrite the config file.
- The shell script wrapper should be modified to pass the config file `-c ${RUNNER_TEMP}/.witness.yml`
- We also need a powershell script for Windows runner (but this should be a separate issue)

ref: https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by colek42** [comment]
I've implimented this in the javascript version
